CREATE TABLE FORECASTER (
	ID int(11) NOT NULL AUTO_INCREMENT,
	LOGIN varchar(250),
	PASSWORD varchar(250),
	EMAIL varchar (250),
	CREATE_DATE DATETIME,
    PRIMARY KEY (id)
);
INSERT INTO FORECASTER (LOGIN, PASSWORD, EMAIL, CREATE_DATE) VALUES ('admin', 'admin', 'you.mail@email.com', NOW());

CREATE TABLE PLAYER (
	ID int(11) NOT NULL AUTO_INCREMENT,
	LASTNAME varchar(255),
	FIRSTNAME varchar(255),
	RANK int(11),
    PRIMARY KEY (id)
);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Djokovic', 'Novak', 1);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Murray', 'Andy', 2);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Federer', 'Roger', 3);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Nadal', 'Rafael', 4);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Wawrinka', 'Stan', 5);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Nishikori', 'Kei', 6);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Thiem', 'Dominic', 7);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Berdych', 'Tomas', 8);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Raonic', 'Milos', 9);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Gasquet', 'Richard', 10);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Goffin', 'David', 11);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Tsonga', 'Jo-Wilfried', 12);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Cilic', 'Marin', 13);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Ferrer', 'David', 14);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Monfils', 'Gael', 15);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Bautista-Agut', 'Roberto', 16);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Isner', 'John', 17);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Simon', 'Gilles', 18);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Kyrgios', 'Nick', 19);
INSERT INTO PLAYER (LASTNAME, FIRSTNAME, RANK) VALUES ('Anderson', 'Kevin', 20);